name: Flutter CI

on:
  push:
  pull_request:
    branches: [ main, feat/*, master ]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Flutter SDK
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1 $HOME/flutter
          export PATH="$HOME/flutter/bin:$PATH"
          flutter --version
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage
